import * as THREE from "three";
import { BufferGeometry } from "three";

/**
 * Set the UV2 map for a Geometry from the default UV map generated by Three.js
 * This is necessary to use an Ambient Occlusion map in the Texture of a Mesh.
 *
 * @param geometry Geometry to self-apply the UV2 map.
 */
export function setUv2Map(geometry: BufferGeometry) {
    geometry.setAttribute(
        "uv2",
        new THREE.Float32BufferAttribute(geometry.attributes.uv.array, 2)
    );
}
